### ISSUE TITLE
Thermaltake Floe Riing RGB 360 support

### ISSUE THREAD

**Issue by nicoulaj** [chestm007/linux_thermaltake_riing#3]
I own a [Thermaltake Floe Riing RGB 360](https://www.thermaltake.com/products-model.aspx?id=C_00003122) and I am a bit confused with the branding, is your project supposed to support it ?

It doesn't seem to work for me, I tried various settings and neither fan speed or lighting seem to be affected by the commands. I did some debugging and it looks like bytes are sent to the USB device without error, so maybe it has a different protocol ?

**Comment by chestm007** [comment]
@nicoulaj hi, i havent tried this with that product, but the physical controlbox appears the same to what im using.

There was an issue with the daemon not properly initializing the device, i'll push a new build soon and let you know when i do if you'd like to try again then?

**Comment by nicoulaj** [comment]
I just tested your change and it works, thanks !

**Comment by cyrus-** [comment]
@nicoulaj can you post your configuration for getting this product working?

**Comment by msbarker** [comment]
@nicoulaj @cyrus- I am interested in the configuration as well! Has anybody got this working yet?

**Comment by nicoulaj** [comment]
Here is my config:
```
controllers:
  - unit: 1
    type: g3
    devices:
      1: Riing Plus
      2: Riing Plus
      3: Riing Plus
      4: Riing Plus
      5: Floe Riing RGB

fan_manager:
  model: curve
  sensor_name: coretemp
  points:
    - [40, 0]
    - [80, 100]

lighting_manager:
  model: 'off'
```
