### ISSUE TITLE
Too much processor usage

### ISSUE THREAD

**Issue by rkmax** [chestm007/linux_thermaltake_riing#41]
**Describe the bug**
I have 120mm TT Premium Plus RGB with 3 fans, as soon set lighting_manager to temperature and fan_manager to curve the process start using between 2-4% of the processor which I think is too much. I have a i7 8700 

here's my config.yml
```
#####################################################################
#
#  This default config file outlines most of the configuration
#   possible using this software, probably don't uncomment it all
#
#####################################################################

controllers:
  - unit: 1
    type: g3
    devices:
      1: Riing Plus
      2: Riing Plus
      3: Riing Plus
#      4: Riing Plus
#      5: Floe Riing RGB
#  - unit: 1
#    type: riingtrio
#    devices:
#      1: Riing Plus  # These are incorrectly specified as Riing Plus
#      2: Riing Plus  # there is nothing in the code that will break this
#      3: Riing Plus  # but we should not be doing confusing things like this
#                     # TODO: implement better fan naming schemes
#  - unit: 2
#    type: g3
#    devices:
#      1: Riing Plus
#      2: Riing Plus
#      3: Riing Plus
#      4: Pacific V-GTX 1080Ti Plus GPU Waterblock
#      5: Pacific W4 Plus CPU Waterblock
#  - unit: 3
#    type: g3
#    devices:
#      1: Riing Plus
#      2: Riing Plus
#      3: Riing Plus
#      4: Pacific V-GTX 1080Ti Plus GPU Waterblock
#      5: Pacific PR22-D5 Plus
#  - unit: 4
#    type: g3
#    devices:
#      1: Riing Plus
#      2: Riing Plus
#      3: Riing Plus
#      4: Pacific V-GTX 1080Ti Plus GPU Waterblock
#      5: Lumi Plus LED Strip
#  - unit: 5
#    type: g3
#    devices:
#      1: Riing Plus
#      2: Riing Plus
#      3: Riing Plus
#      4: Riing Plus
#      5: Lumi Plus LED Strip

fan_manager:
#  model: locked_speed
#  speed: 55

#  model: temp_target
#  target: 38
#  sensor_name: k10temp
#  multiplier: 5

  model: curve
  points:
    - [30, 0]  # [temp(*C), speed(0-100%)]
    - [40, 50]
    - [60, 100]
  sensor_name: coretemp

lighting_manager:
# speed: normal

  model: temperature
  sensor_name: coretemp
  cold: 30
  target: 40
  hot: 60
  speed: extreme

#  model: alternating
#  odd_rgb:
#    r: 50
#    g: 0
#    b: 0
#  even_rgb:
#    r: 0
#    g: 50
#    b: 0

#  model: full
  r: 87
  g: 198
  b: 63

#  model: flow

#  model: spectrum

#  model: ripple
#  r: 50
#  g: 0
#  b: 0

#  model: blink
#  r: 50
#  g: 0
#  b: 0

#  model: pulse
#  r: 50
#  g: 0
#  b: 0

```

**Expected behavior**
too use 1% or less I have a processor with 6 cores and 12 threads basically for regular use is always under ~41°C and the noctua fan round ~200rpm and with the previous settings will keep up 46°C and processor fan around the double

**Desktop (please complete the following information):**
 - Archlinux
 - Linux desktop 5.6.12-arch1-1 #1 SMP PREEMPT Sun, 10 May 2020 10:43:42 +0000 x86_64 GNU/Linux
