### ISSUE TITLE
Cannot change RGB values or effects on Riing Trio 14 

### ISSUE THREAD

**Issue by diffficult** [chestm007/linux_thermaltake_riing#46]
linux_thermaltake_riing seems to be working just fine when setting fan speeds and modes. But I can't change RGB values or effects no matter what.

- `config.yml` I'm using:

```
controllers:
  - unit: 1
    type: riingtrio
    devices:
      1: Riing Trio
      2: Riing Trio
      3: Riing Trio
fan_manager:
  model: curve
  points:
    - [0, 0]  # [temp(*C), speed(0-100%)]
    - [40, 40]
    - [55, 50]
    - [60, 65]
    - [80, 100]
  sensor_name: zenpower
lighting_manager:
  model: temperature
  sensor_name: zenpower
  cold: 40
  target: 55
  hot: 70
  speed: slow
```

- `systemctl status` after setting up a fan curve

```
● linux-thermaltake-rgb.service
     Loaded: loaded (/usr/lib/systemd/system/linux-thermaltake-rgb.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2020-11-24 19:41:26 -03; 1s ago
   Main PID: 94028 (linux-thermalta)
      Tasks: 5 (limit: 77062)
     Memory: 19.6M
     CGroup: /system.slice/linux-thermaltake-rgb.service
             └─94028 /usr/bin/python /usr/bin/linux-thermaltake-rgb

nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]: model Riing Trio not found. controller: <linux_thermaltake_rgb.controllers.Ther>
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]: model Riing Trio not found. controller: <linux_thermaltake_rgb.controllers.Ther>
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]: model Riing Trio not found. controller: <linux_thermaltake_rgb.controllers.Ther>
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]: Starting fan manager (curve [[  0   0]
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]:  [ 40  40]
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]:  [ 55  50]
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]:  [ 60  65]
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]:  [ 80 100]])...
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]: /usr/lib/python3.8/site-packages/linux_thermaltake_rgb/daemon/config.py:42: YAM>
nov 24 19:41:27 COMPUTER linux-thermaltake-rgb[94028]:   config = yaml.load(cfg)
```

- `lsusb` readout from the controller I'm using (the standard included with the kit)

```
Bus 001 Device 004: ID 264a:2135 Thermaltake
```

any suggestions on how to do it?
